name: Scrape Patch Notes

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日0時（UTC）に自動実行
  workflow_dispatch:      # 手動でも実行できるように

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r scraper/requirements.txt

      - name: Run scraper
        run: python scraper/patch_scraper.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "WR.GG_github-actions[bot]"
          git config user.email "WR.GG_github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update data from scraper" || echo "No changes"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}}}
