name: Scrape Patch Notes

on:
  schedule:
    - cron: '0 0 * * 5'  # 毎週金曜0時（UTC）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r scraper/requirements.txt

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -o '[0-9]\+' | head -1)
          echo "Chrome Version: $CHROME_VERSION"
          LATEST_DRIVER=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          echo "ChromeDriver Version: $LATEST_DRIVER"
          wget -O chromedriver.zip "https://chromedriver.storage.googleapis.com/${LATEST_DRIVER}/chromedriver_linux64.zip"
          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version


      - name: Run scraper
        run: python scraper/patch_scraper.py

      # Node.js セットアップと docs ビルド追加
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Node dependencies
        run: npm install
        working-directory: wrgg-frontend

      - name: Build docs
        run: npm run build-docs
        working-directory: wrgg-frontend

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "WR.GG_github-actions[bot]"
          git config user.email "WR.GG_github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update data and docs from scraper" || echo "No changes"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
